#!/bin/sh
# Regenerate data/oui-802154.tsv: the MA-L (24-bit) assignments of vendors that make
# IEEE 802.15.4 radios or devices, from Wireshark's copy of the IEEE registry.
#
# The binary embeds this table so that vendor names work anywhere. The full registry
# is used instead where the system has it (see src/oui.lisp), so the table only needs
# to cover the vendors a sniffer actually meets.
#
#   tools/make-oui-table.sh > data/oui-802154.tsv
set -eu
VENDORS='Texas Instrum|Silicon Lab|Ember Corp|Jennic|NXP|Philips Light|Signify|dresden|Resideo|Honeywell|ubisys|Develco|Legrand|Nest Labs|SAMJIN|Nordic Semi|Espressif|IKEA|Schneider Elec|Atmel|Microchip|Digi International|Freescale|STMicro|Lumi United|Tuya|Aqara|Sonoff|Hue|Bosch|Danfoss|Eurotronic|Centralite|SmartThings|Sengled|LEDVANCE|OSRAM|GE Lighting|Leviton|Lutron|Yale|Assa Abloy|Kwikset|Ecobee|Eve Systems|Nanoleaf|Wemo|Belkin|Allterco|Shelly|Ezviz|Amazon Tech|Google|Apple'
echo "# OUI	Vendor	(generated by tools/make-oui-table.sh from $(tshark --version | head -1))"
tshark -G manuf | awk -F'\t' -v re="$VENDORS" '
  $1 ~ /^[0-9A-F][0-9A-F]:[0-9A-F][0-9A-F]:[0-9A-F][0-9A-F] *$/ && $3 ~ re {
    gsub(/ +$/, "", $1); gsub(/ +$/, "", $3); print $1 "\t" $3 }' | sort -u
